
#todo : sns configurations for different environments
#todo : secretsmanager configuration of different environments
#todo : construct arns

service: Github-to-S3

provider:
  name: aws
  runtime: python3.6
  profile: serverless
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "sns:Publish"
      Resource:
        - {"Fn::Join" : ["", ["arn:aws:sns:${self:custom.region}:", { "Ref" : "AWS::AccountId" }, ":${self:custom.githubFileToCopy}" ] ]}
    - Effect: 'Allow'
      Action:
        - "secretsmanager:*"
      Resource:
        - "arn:aws:secretsmanager:us-east-1:670533574044:secret:/prod/githubCopy/appConfig-GxQvt5"
        - "arn:aws:secretsmanager:us-east-1:670533574044:secret:prod/s3/appKeys-95tOPE"
    - Effect: 'Allow'
      Action:
        - "kms:*"
      Resource:
        - "arn:aws:kms:us-east-1:670533574044:key/f1f6bf8b-c32c-4818-82cf-7e3622c87c09"

custom:
  stage: ${opt:stage , self.provider.stage}
  region: ${opt:region , self.provider.region}
  githubFileToCopy: "${self:service}-github-file-to-copy-${self:custom.stage}"

package:
  include:
    - library/**

functions:
  githubWebhook:
    handler: handler.githubWebhook
    events:
      - http:
          path: webhook/githubWebhook
          method: post
    enviornment:
      snsarn: { "Fn::Join" : ["", ["arn:aws:sns:${self:custom.region}:", { "Ref" : "AWS::AccountId" }, ":${self:custom.githubFileToCopy}" ] ]  }
  githubFileCopy:
    handler: handler.githubFileCopy
    events:
      - sns: ${self:custom.githubFileToCopy}

